name: Post Latest Blog from RSS to Bluesky

on:
  workflow_run:
    workflows: ["Schedule Posts", "Pages Build and Deployment"]
    types:
      - completed

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      # Ensure that both workflows have completed successfully
      - name: Check if previous workflows were successful
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow did not succeed. Exiting."
            exit 1
          fi

      # Install xmllint
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      # Fetch Latest Blog Post
  id: fetch_post
  run: |
    # Replace this with your RSS feed URL
    RSS_FEED_URL="https://tacticsjournal.com/feed"
    
    # Use curl to fetch RSS and xmllint to parse the latest post
    echo "Fetching RSS feed from $RSS_FEED_URL..."
    response=$(curl -s "$RSS_FEED_URL")
    echo "Fetched response: $response"
    
    description=$(echo "$response" | xmllint --xpath "string(//item[1]/description)" -)
    echo "Parsed description: $description"
    
    url=$(echo "$response" | xmllint --xpath "string(//item[1]/link)" -)
    echo "Parsed URL: $url"
    
    # Format the text for Bluesky
    preview="$description $url"
    echo "Preview to post: $preview"
    echo "preview=$preview" >> $GITHUB_ENV

      # Post to Bluesky
      - name: Post to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "${{ env.post }}"
          link-preview-url: "$url"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BSS }}
