name: Post Latest Blog from RSS to Bluesky

on:
  workflow_run:
    workflows: ["Schedule Posts", "Pages Build and Deployment"]
    types:
      - completed

jobs:
  fetch-and-post:
    runs-on: ubuntu-latest

    steps:
      # Ensure that both workflows have completed successfully
      - name: Check if previous workflows were successful
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow did not succeed. Exiting."
            exit 1
          fi

      # Install xmllint
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      # Fetch the latest blog post from RSS feed
      - name: Fetch Latest Blog Post
        id: fetch_post
        run: |
          # Replace this with your RSS feed URL
          RSS_FEED_URL="https://tacticsjournal.com/feed"
         
          # Use curl to fetch RSS and xmllint to parse the latest post
          response=$(curl -s "$RSS_FEED_URL")
          description=$(echo "$response" | xmllint --xpath "string(//item[1]/title)" -)
          url=$(echo "$response" | xmllint --xpath "string(//item[1]/link)" -)
          pub_date=$(echo "$response" | xmllint --xpath "string(//item[1]/pubDate)" -)
          
          # Log the pub_date
           echo "The publication date of the latest post is: $pub_date" >> script.log

          # Get today's date
          today=$(date +'%a, %d %b %Y')

          # Compare the publication date with today's date
          if [[ "$pub_date" != "$today" ]]; then
            echo "The blog post is not from today. Exiting."
            exit 0
          fi

          # Format the text for Bluesky
          preview="$description $url"
          echo "preview=$preview" >> $GITHUB_ENV
          echo "rss_url=$url" >> $GITHUB_ENV

      # Post to Bluesky
      - name: Post to Bluesky
        uses: myConsciousness/bluesky-post@v5
        with:
          text: "${{ env.preview }}"
          link-preview-url: "${{ env.rss_url }}"
          identifier: tacticsjournal.com
          password: ${{ secrets.BSS }}
