name: Validate Front Matter

on:
  push:
    paths:
      - _posts/**

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version you are using

      - name: Install yaml-lint
        run: gem install yaml-lint

      - name: Validate latest month's front matter
        run: |
          # Get the latest year and month directory
          latest_dir=$(find ./_posts -type d -exec basename {} \; | sort -nr | head -2 | tr '\n' '/')
          target_path="./_posts/${latest_dir}"
          
          # Validate all Markdown files in the latest directory
          if [ -d "$target_path" ]; then
            find "$target_path" -name "*.md" -exec yaml-lint {} \;
          else
            echo "No markdown files found for the latest month."
          fi