name: Validate Front Matter

on:
  push:
    paths:
      - _posts/**

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version you are using

      - name: Install yaml-lint
        run: gem install yaml-lint

      - name: Debug and Validate latest and next month's front matter
        run: |
          # Get the current date
          current_year=$(date +'%Y')
          current_month=$(date +'%m')

          # Debug: Print current year and month
          echo "Current Year: $current_year"
          echo "Current Month: $current_month"

          # Calculate next month
          next_month=$(date -d "$current_year-$current_month-01 +1 month" +'%m')
          next_year=$(date -d "$current_year-$current_month-01 +1 month" +'%Y')

          # Debug: Print next year and month
          echo "Next Year: $next_year"
          echo "Next Month: $next_month"

          # Construct paths for latest and next month's directories
          latest_dir="./_posts/$current_year/$current_month"
          next_dir="./_posts/$next_year/$next_month"

          # Debug: Print the paths it will check
          echo "Checking latest directory: $latest_dir"
          echo "Checking next directory: $next_dir"

          # Validate markdown files in the latest month
          if [ -d "$latest_dir" ]; then
            echo "Validating markdown files in $latest_dir..."
            find "$latest_dir" -name "*.md" -exec echo "Found file: {}" \; -exec yaml-lint {} \;
          else
            echo "No directory found for the latest month: $latest_dir"
          fi

          # Validate markdown files in the next month
          if [ -d "$next_dir" ]; then
            echo "Validating markdown files in $next_dir..."
            find "$next_dir" -name "*.md" -exec echo "Found file: {}" \; -exec yaml-lint {} \;
          else
            echo "No directory found for the next month: $next_dir"
          fi