name: Validate Front Matter

on:
  push:
    paths:
      - _posts/**

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version you are using

      - name: Install yaml-lint
        run: gem install yaml-lint

      - name: Validate front matter
        run: |
          find ./_posts -name "*.md" -exec yaml-lint {} \;