name: Validate Front Matter

on:
  push:
    paths:
      - _posts/**

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Specify the Ruby version you are using

      - name: Install required gems
        run: gem install yaml-lint

      - name: Validate front matter of Markdown files
        run: |
          # Get the current date
          current_year=$(date +'%Y')
          current_month=$(date +'%m')

          # Debug: Print current year and month
          echo "Current Year: $current_year"
          echo "Current Month: $current_month"

          # Calculate next month
          next_month=$(date -d "$current_year-$current_month-01 +1 month" +'%m')
          next_year=$(date -d "$current_year-$current_month-01 +1 month" +'%Y')

          # Debug: Print next year and month
          echo "Next Year: $next_year"
          echo "Next Month: $next_month"

          # Construct paths for latest and next month's directories
          latest_dir="./_posts/$current_year/$current_month"
          next_dir="./_posts/$next_year/$next_month"

          # Debug: Print the paths it will check
          echo "Checking latest directory: $latest_dir"
          echo "Checking next directory: $next_dir"

          # Function to validate front matter
          validate_front_matter() {
            local dir=$1
            if [ -d "$dir" ]; then
              echo "Validating markdown files in $dir..."
              for file in "$dir"/*.md; do
                if [ -f "$file" ]; then
                  echo "Checking file: $file"
                  front_matter=$(awk '/^---/{flag=!flag} flag' "$file")
                  echo "$front_matter" | yaml-lint || echo "YAML validation failed for $file"
                fi
              done
            else
              echo "No directory found: $dir"
            fi
          }

          # Validate markdown files in latest and next month directories
          validate_front_matter "$latest_dir"
          validate_front_matter "$next_dir"